#! /usr/bin/env bash

script_file="$(readlink -f "${BASH_SOURCE[0]}")"
local_folder="$(dirname "${script_file}")"
share_folder="${local_folder}"

# Search upwards for share folder
while [ -n "${share_folder}" -a "$(basename "${share_folder}")" != "Suites" ]
do
    share_folder="$(dirname "${share_folder}")"
done

reactor::run() {
    exec "${share_folder}/tools/webserve" \
        --static="${share_folder}/static" \
        --module="${share_folder}/plugins/management_plugin" \
        --port=$(get_unused_port || echo 11111)
}
