#! /usr/bin/env bash
set -x

script_file="$(readlink -f "${BASH_SOURCE[0]}")"
local_folder="$(dirname "${script_file}")"
share_folder="$(readlink -f "${local_folder}/../..")"
suite_folder="${__SUITE_FOLDER__}"

reactor::run() {
    "${share_folder}/tools/webserve" \
        --static="${share_folder}/static" \
        --module="${share_folder}/plugins/management_plugin" \
        --port=11100
}
